name: Latest blog post workflow
on:
  push:
    branches:
    - main
  schedule:
    # Runs once a day at 6:00
    - cron: '0 6 * * *'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          #feed_list: 'https://dev.to/feed/rahuldkjain, https://medium.com/feed/@rahuldkjain'
          feed_list: 'https://yanncharlou.fr/index.xml'